### ISSUE TITLE
mission.py example broken (type object 'MissionItem' has no attribute 'CameraAction')

### ISSUE THREAD

**Issue by petergerten** [mavlink/MAVSDK-Python#200]
Trying to execute the mission.py example I get:
```
Waiting for mavsdk_server to be ready...
Connected to mavsdk_server!
Waiting for drone to connect...
Drone discovered with UUID: 255
Traceback (most recent call last):
  File "mission.py", line 103, in <module>
    loop.run_until_complete(run())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "mission.py", line 32, in run
    MissionItem.CameraAction.NONE,
AttributeError: type object 'MissionItem' has no attribute 'CameraAction'
```
I was able to reproduce this in a clean environment - Dockerfile:
```
FROM ubuntu:20.04
RUN apt-get update && apt-get install -y python3-pip git vim
RUN pip3 install mavsdk
```

**Comment by julianoes** [comment]
@JonasVautherin could that be the problem you discovered and fixed in https://github.com/mavlink/MAVSDK-Python/pull/194 ? If so it should be fixed in 0.8.0.

**Comment by JonasVautherin** [comment]
Yes it could be. @petergerten would you mind trying with 0.8.x?

**Comment by petergerten** [comment]
@JonasVautherin I was actually using 0.8.0.
Just upgraded to 0.8.2 and the same issue remains the same.
